foreground #d3c6aa
background #272e33
cursor #7fbbb3
cursor_text_color #272e33
selection_foreground #d3c6aa
selection_background #414b50
active_tab_foreground #d3c6aa
active_tab_background #2e383c
inactive_tab_foreground #859289
inactive_tab_background #272e33
color0 #2e383c
color1 #e67e80
color2 #a7c080
color3 #e69875
color4 #7fbbb3
color5 #7fbbb3
color6 #83c092
color7 #bdae93
color8 #859289
color9 #e67e80
color10 #a7c080
color11 #e69875
color12 #7fbbb3
color13 #7fbbb3
color14 #83c092
color15 #d3c6aa
