$activeBorderColor = rgb(8A8A8D)

general {
        #   col.inactive_border = rgba(8A8A8D00)
        col.active_border = rgba(DDDDDD33)

}

group {
    col.border_active = $activeBorderColor
}

misc {
    background_color = rgba(1D1011FF)
    focus_on_activate = true
}

plugin {
    hyprbars {
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_blur = true
        bar_padding = 10
        bar_title_enabled= false
        bar_button_padding = 10
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(1F2020ff)
        bar_color = rgba(1E1E1E66)

        col.text = rgba(1F2020ff)

        hyprbars-button = rgb(333333), 20,󰅖, hyprctl dispatch killactive
        hyprbars-button = rgb(333333), 20,󰖰, hyprctl dispatch movetoworkspacesilent special:scratch
        inactive_button_color = rgba(31313100)
        on_double_click = hyprctl dispatch fullscreen 1
        roundness = 12

    }
}

windowrulev2 = bordercolor rgba(FFB2BCAA) rgba(FFB2BC77),pinned:1
# Sets the bar color in red for all windows that have 'myClass' as a class
# windowrule = plugin:hyprbars:nobar, class:^(code)
# windowrule = plugin:hyprbars:nobar, class:^(windsurf)
# windowrule = plugin:hyprbars:nobar, class:^(org.gnome.Nautilus)
# windowrule = plugin:hyprbars:nobar, class:^(google-chrome)
