# General Rules
layerrule = noanim, selection # Remove 1px border hyprshot screenshots

windowrulev2 = bordercolor rgba(3C3C3Cff), fullscreen:1

# windowrulev2 = rounding 10, fullscreen:1
layerrule = noanim, hyprpicker
windowrule = fullscreen, class:(org.gnome.Loupe)

# fixes mpv fullscreen black screen issue
windowrule = suppress_event maximize, match:class .*
windowrule = content none, class:mpv

# Just dash of opacity by default
# windowrule = opacity 0.97 0.4, match:class .*

# idleinhibit rules
windowrule = idleinhibit fullscreen, class:^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$
windowrule = idleinhibit fullscreen, class:^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$

# Hyde Wlogout Enable Blur
layerrule = blur, wlogout
layerrule = blur, /home/shohan11d/.config/wlogout/hyde-waybar.sh
layerrule = blur,logout_dialog

# Opacity Rules, Tags, Floats...
windowrule = tag +floating-window, class:(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus), title:^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)
windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 875 600, tag:floating-window
windowrule = float, class:org.gnome.Calculator

# Picture-in-picture overlays
windowrule = tag +pip, title:(Picture.?in.?[Pp]icture)
windowrule = float, tag:pip
windowrule = pin, tag:pip
windowrule = size 600 338, tag:pip
windowrule = keepaspectratio, tag:pip
windowrule = noborder, tag:pip
windowrule = opacity 1 1, tag:pip
windowrule = move 100%-w-40 4%, tag:pip

# Launchers need to be FAST
layerrule = noanim, gtk4-layer-shell
layerrule = ignorezero, gtk-layer-shell
layerrule = blur, gtk-layer-shell


# Vicinae launcher
layerrule = blur,vicinae
layerrule = ignorealpha 0, vicinae
layerrule = noanim, vicinae



windowrulev2 = float, class:^(waypaper|gnome-disks)$
windowrulev2 = center, class:^(waypaper|gnome-disks)$
windowrulev2 = size 80% 80%, class:^(waypaper|gnome-disks)$

windowrulev2 = float, title:(?i)sign[\s-]*in
windowrulev2 = center, title:(?i)sign in



# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = float, title:^(pavucontrol)$
windowrule = float, title:^(blueman-manager)$
windowrule = float, title:^(nm-connection-editor)$
windowrule = float, title:^(qalculate-gtk)$

# Browser Picture in Picture
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = move 69.5% 4%, title:^(Picture-in-Picture)$

# idleinhibit
windowrule = idleinhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen

#xwayland related rules
# when moving objects in resolve a large border is produced 
# This rule prevents that and serves as a template for any problematic xwayland apps
windowrule = noblur, class:^(\bresolve\b)$, xwayland:1
# This is a general rule for xwayland apps but can have other consequences 
# for one user it impacted EMACs so it's disabled by default 
# It's here as a reference or for quick triage of xwayland ap
#windowrule = noblur, xwayland:1

# Waybar blur
layerrule = blur, waybar

layerrule = ignorealpha 0.01, waybar  # Forces blur on very transparent areas
layerrule = ignorezero, waybar 

windowrulev2 = bordersize 0, fullscreen:1
# Multiple classes opacity rule
windowrulev2 = opacity 0.95 0.9, class:^(org.gnome.Nautilus|Thunar|Files)$
windowrulev2 = opacity 1.0 override 1.0 override, class:^(google-chrome|brave-browser|code|windsurf|vim|neovim|mpv)$



# Apply to all windows on the "special" workspace
windowrulev2 = workspace:special class:.* opacity:0.85 border:rgba(FF4500AA) border_size:2 blur:5
