# MPV configuration file
osd-bar=no
border=no
#video-sync=display-resample
drag-and-drop=replace 
volume-max=100
cursor-autohide=500 
no-window-dragging
keep-open=yes

alang=en,ja
slang=en,ja
vlang=en,ja


target-colorspace-hint=no


