
source=monitors.conf
source=conf/envs.conf
source=conf/variables.conf
source=conf/execs.conf
source=conf/general.conf
source=conf/rules.conf
source=conf/colors.conf
source=conf/keybinds.conf
source=conf/workspace.conf