$activeBorderColor = rgb(8A8A8D)

general {

    # color - cosmic blue
    # col.active_border = rgba(63bac6ff)
    col.active_border = rgba(88888899)
    col.inactive_border = rgba(44444466)

}


plugin {
    hyprbars {
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_blur = true
        bar_title_enabled= false
        bar_button_padding = 10
        bar_precedence_over_border = true
        bar_part_of_window = true
        # my fav
        # bar_color = rgba(1b1b1bcc)
        bar_color = rgba(1E1E1E99)

        col.text = rgba(1F2020ff)

        hyprbars-button = rgba(1b1b1b00), 20,, hyprctl dispatch killactive
        hyprbars-button = rgba(1b1b1b00), 20,, hyprctl dispatch movetoworkspacesilent special:scratch
        on_double_click = hyprctl dispatch fullscreen 1
        roundness = 0

    }
}

windowrule = border_color rgba(FFB2BCAA) rgba(FFB2BC77), match:pin 1
# windowrule = border_color rgb(FAFAFA), match:fullscreen 1
windowrule = border_size 0, match:fullscreen 1