$activeBorderColor = rgb(8A8A8D)

general {
    # --- Inactive color ---
    col.inactive_border = rgba(595959aa)

    ##### Active color #####
    # color - subtle white
    col.active_border = rgba(DDDDDD80)
    # color - cosmic blue
    col.active_border = rgba(63bac6ff)
    # color - end4
    # col.active_border = rgba(0DB7D455)


}


plugin {
    hyprbars {
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_blur = false
        bar_title_enabled= false
        bar_button_padding = 10
        bar_precedence_over_border = true
        bar_part_of_window = true
        bar_color = rgb(1b1b1b)
        # bar_color = rgb(1f2021)
        # cosmic 
        # bar_color = rgb(1b1b1b)

        col.text = rgba(1F2020ff)

        hyprbars-button = rgb(1b1b1b), 20,, hyprctl dispatch killactive
        hyprbars-button = rgb(1b1b1b), 20,, hyprctl dispatch movetoworkspacesilent special:scratch
        on_double_click = hyprctl dispatch fullscreen 1
        roundness = 0

    }
}

windowrule = border_color rgba(FFB2BCAA) rgba(FFB2BC77), match:pin 1
windowrule = border_color rgb(FAFAFA), match:fullscreen 1
