# --- Wayland ---
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# --- Applications ---
env = XDG_DATA_DIRS,$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop

# --- Themes ---
env = QT_QPA_PLATFORM, wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XDG_MENU_PREFIX, plasma-

# --- Kitty single instance ---
env = TERMINAL,kitty -1

# --- Misc ---
ecosystem {
  no_update_news = true
  no_donation_nag = true
}

