
# Apps
$terminal = ~/.config/hypr/conf/scripts/launch_first_available.sh "kitty -1" "foot" "alacritty" "wezterm" "konsole" "kgx" "uxterm" "xterm"
$fileManager = ~/.config/hypr/conf/scripts/launch_first_available.sh "nautilus --new-window" "dolphin" "nemo" "thunar" "kitty -1 fish -c yazi"
$browser = ~/.config/hypr/conf/scripts/launch_first_available.sh "google-chrome" "google-chrome-stable" "google-chrome-unstable"  "firefox" "brave" "chromium" "microsoft-edge-stable" "opera" "librewolf"
$codeEditor = ~/.config/hypr/conf/scripts/launch_first_available.sh "antigravity" "windsurf" "code" "cursor" "zed" "zedit" "zeditor" "kate" "gnome-text-editor" "emacs" "command -v nvim && kitty -1 nvim" "command -v micro && kitty -1 micro"
$officeSoftware = ~/.config/hypr/conf/scripts/launch_first_available.sh "wps" "onlyoffice-desktopeditors" "libreoffice"
$textEditor = ~/.config/hypr/conf/scripts/launch_first_available.sh "kate" "gnome-text-editor" "emacs"
$volumeMixer = ~/.config/hypr/conf/scripts/launch_first_available.sh "pavucontrol-qt" "pavucontrol"
$taskManager = ~/.config/hypr/conf/scripts/launch_first_available.sh "gnome-system-monitor" "plasma-systemmonitor --page-name Processes" "command -v btop && kitty -1 fish -c btop"


# Variables
$mod = Super
$altMod  = Alt
$mod1  = Alt
$webApp  = $browser --app
$browser = uwsm app -- google-chrome --new-window --ozone-platform=wayland